### ISSUE TITLE
Enhancer does not work with ebean 11.5.1

### ISSUE THREAD

**Issue by npokr** [ebean-orm/ebean-idea-enhancer#24]
IDE:
IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3622.25, built on November 9, 2017
...
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Latest plugin from JetBrains repository (11.1.1) does not enhance sources, written for 11.5.1 - when I run simple junit test from IDE, it gives out "java.lang.NoSuchMethodError: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)Ljava/beans/PropertyChangeEvent;".
Plugin, builded from this repository latest sources (11.5.2-SNAPSHOT), behaves the same way.
Both this plugins can enhance sources for 11.1.1.

**Comment by rbygrave** [comment]
Yes interesting.  I did release 11.5.1 12 days ago ... but yes, it doesn't show up with the prior 11.1.1 version only available.

I have:
```
Dear Rob Bygrave,

Version 11.5.1 of the Ebean 11.x Enhancement plugin has been approved by JetBrains and is now publicly available by the 
following link: https://plugins.jetbrains.com/plugin/10082-ebean-11-x-enhancement/update/40258.
```
Hmmm, something went wrong.
Ok, releasing another version so have to see how that goes.

**Comment by rbygrave** [comment]
Ok, uploaded the next release of the plugin which is 11.5.3.

--- 
Dear Rob Bygrave,

Thank you for submitting a 11.5.3 version of Ebean 11.x Enhancement plugin, it has been successfully uploaded to the plugins repository and now pending JetBrains' review and approval in order to be publicly available.

All new updates are normally reviewed within two business days. You will receive a notification as soon as status of this review changes.

In the meantime, you can always access your update via direct link: https://plugins.jetbrains.com/plugin/10082-ebean-11-x-enhancement/update/40658, but please note that it won't be publicly available (e.g. in search results and in the product) until approved by JetBrains.

**Comment by rbygrave** [comment]
Closing, updated plugin released and available.
